# Generated by Django 5.1 on 2024-08-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmdirect', '0002_remove_usermodel_email_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('F', 'Farmer'), ('B', 'Buyer')], default='buyer', max_length=1),
        ),
    ]
