# Generated by Django 5.1 on 2024-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmdirect', '0003_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
