# Generated by Django 5.1 on 2024-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmdirect', '0006_alter_usermodel_max_otp_try_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default_username', max_length=50, null=True, unique=True),
        ),
    ]
